name: Print Branch Name on Pull Request

on:
  pull_request:
    branches:
      - "*"

jobs:
  print-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: echo "Branch name is ${{ github.head_ref }}"
