name: CI Injection Test

on:
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Injection
        run: |
          echo "[*] Running branch ref:"
          eval "${{ github.head_ref }}"
