name: PoC 

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  poc:
    runs-on: ubuntu-latest
    steps:
      # 취약 액션 호출 (원본 구조 유지)
      - name: Run vulnerable action
        uses: ./actions/setup/variable
