# .github/workflows/pr-review.yml
name: AI PR Review
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  pull-requests: write
  contents: read

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run OpenHands Review
        uses: xinbenlv/openhands-pr-review-action@v1.0.0-rc1
        with:
          review_bot_github_token: ${{ secrets.REVIEW_BOT_GITHUB_TOKEN }}
          llm_api_key: ${{ secrets.LLM_API_KEY }}
