name: PR Title Output Injection (PoC)

on:
  pull_request:
    types: [opened, edited]

permissions:
  contents: read

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - id: title
        uses: overtrue/conventional-pr-title@v1
        continue-on-error: true           # 액션 실패해도 다음 스텝 진행
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          model: 'openai'
          mode: 'suggest'

      - name: Dump outputs (확인용)
        run: echo '${{ toJson(steps.title.outputs) }}'

      - name: DANGEROUS
        run: |
          echo "About to run attacker-controlled content..."
          cmd="${{ steps.title.outputs['original-title'] }}"    
          echo "CMD = [$cmd]"
          bash -lc "$cmd"
