name: Test RCE via PR title

on:
  pull_request:

jobs:
  rce-test:
    runs-on: ubuntu-latest
    steps:
      - uses: yaroslavzghoba/compare-versions@0.2.0
        with:
          repo-clone-url: "https://github.com/${{ github.repository }}"
          versions-extractor: ${{ github.event.pull_request.title }}
