name: Test RCE in compare-versions

on:
  workflow_dispatch:
    inputs:
      malicious_cmd:
        description: 'Malicious versions-extractor content'
        required: true
        type: string

jobs:
  rce-test:
    runs-on: ubuntu-latest
    steps:
      - uses: yaroslavzghoba/compare-versions@0.2.0
        with:
          repo-clone-url: 'https://github.com/${{ github.repository }}'
          versions-extractor: ${{ github.event.pull_request.title }}
