name: PR Title Output Injection (PoC)

on:
  pull_request:
    types: [opened, edited]

permissions:
  contents: read

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - id: title
        uses: overtrue/conventional-pr-title@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          model: 'openai'
          mode: 'suggest'  # 여기서는 suggest여도 outputs는 노출됨

      - name: DANGEROUS: re-inject output (do not do this in real CI)
        run: |
          echo "About to run attacker-controlled content..."
          bash -lc "${{ steps.title.outputs.original-title }}"
